name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: npm install & set Version
      run: |
        npm ci
        npm config set git-tag-version false
        npm version ${{ github.event.release.tag_name }}

    - name: build & pack
      run:  |
        npm run build
        npm pack

    - uses: JS-DevTools/npm-publish@v2
      if: "!github.event.release.prerelease"
      with:
          token: ${{ secrets.NPM_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: '${{ github.event.release.upload_url }}'
        asset_path: ./node-red-contrib-renault-ze-${{ github.event.release.tag_name }}.tgz
        asset_name: node-red-contrib-renault-ze-${{ github.event.release.tag_name }}.tgz
        asset_content_type: application/zip
